/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.sm-check-btn[_ngcontent-%COMP%] {\r\n    min-width: 220px;\r\n    text-align:left;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVrdHkvU2VydmljZU1hcEFuZzQvU2VydmljZU1hcC9zcmMvU2VydmljZU1hcC93d3dyb290L2FwcC91c2Vycy91c2VyLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovUHJvamVrdHkvU2VydmljZU1hcEFuZzQvU2VydmljZU1hcC9zcmMvU2VydmljZU1hcC93d3dyb290L2FwcC91c2Vycy91c2VyLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
