/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['table[_ngcontent-%COMP%] {\r\n    width: 100%;\r\n    height:95%;\r\n}\r\n\r\nth[_ngcontent-%COMP%] {\r\n     white-space: nowrap;  \r\n     height:55px;\r\n}\r\n\r\n\r\n\r\n.sm-wrap-tekst[_ngcontent-%COMP%]{\r\n    word-wrap: break-word;\r\n}\r\n\r\n.sm-common-width[_ngcontent-%COMP%]{\r\n    width: 150px;\r\n}\r\n\r\n.sm-email-col-width-th[_ngcontent-%COMP%]{\r\n    min-width:255.2px !important;\r\n    width:255.2px !important;\r\n}\r\n.sm-email-col-width-td[_ngcontent-%COMP%]{\r\n    min-width:254px !important;\r\n    width:254px !important;\r\n}\r\n\r\n.sm-IsSuperUser-col-width[_ngcontent-%COMP%]{\r\n    width:180px;\r\n}\r\n\r\n.sm-last-coll-with[_ngcontent-%COMP%] {\r\n    width:100%;\r\n}\r\n\r\n.panel-primary[_ngcontent-%COMP%]    > .panel-heading[_ngcontent-%COMP%] {\r\n    border-color: white;\r\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVrdHkvU2VydmljZU1hcEFuZzQvU2VydmljZU1hcC9zcmMvU2VydmljZU1hcC93d3dyb290L2FwcC91c2Vycy91c2VyLWxpc3QuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWt0eS9TZXJ2aWNlTWFwQW5nNC9TZXJ2aWNlTWFwL3NyYy9TZXJ2aWNlTWFwL3d3d3Jvb3QvYXBwL3VzZXJzL3VzZXItbGlzdC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
