/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../app/users/user-module';
import * as i2 from '../../node_modules/angular2-busy/build/busy.component.ngfactory';
import * as i3 from '../../node_modules/angular2-busy/build/busy-backdrop.component.ngfactory';
import * as i4 from '../../node_modules/ngx-bootstrap/modal/modal-backdrop.component.ngfactory';
import * as i5 from '../../node_modules/ngx-bootstrap/popover/popover-container.component.ngfactory';
import * as i6 from '../../node_modules/ngx-bootstrap/tooltip/tooltip-container.component.ngfactory';
import * as i7 from '../../node_modules/ng2-toastr/src/toast-container.component.ngfactory';
import * as i8 from './user-list.component.ngfactory';
import * as i9 from './user.component.ngfactory';
import * as i10 from '@angular/forms';
import * as i11 from '@angular/common';
import * as i12 from 'angular2-busy/build/busy.module';
import * as i13 from '@angular/platform-browser';
import * as i14 from '@angular/animations/browser';
import * as i15 from '@angular/platform-browser/animations';
import * as i16 from '@angular/animations';
import * as i17 from 'angular2-busy/build/busy-config';
import * as i18 from '../../../app/shared/busy-config';
import * as i19 from 'angular2-busy/build/busy.service';
import * as i20 from 'ngx-bootstrap/positioning/positioning.service';
import * as i21 from 'ngx-bootstrap/component-loader/component-loader.factory';
import * as i22 from 'ngx-bootstrap/popover/popover.config';
import * as i23 from 'ngx-bootstrap/tooltip/tooltip.config';
import * as i24 from 'ng2-toastr/src/toast-options';
import * as i25 from '../../../app/shared/toastr-custom-option';
import * as i26 from 'ng2-toastr/src/toast-manager';
import * as i27 from '../../../app/shared/toastr.service';
import * as i28 from '../../../app/users/user.service';
import * as i29 from '@angular/http';
import * as i30 from '../../../app/users/user-guard.service';
import * as i31 from '@angular/router';
import * as i32 from 'ngx-bootstrap/modal/modal.module';
import * as i33 from 'ngx-bootstrap/popover/popover.module';
import * as i34 from 'ngx-bootstrap/tooltip/tooltip.module';
import * as i35 from 'ng2-toastr/src/toast.module';
import * as i36 from 'primeng/components/common/shared';
import * as i37 from 'primeng/components/dropdown/dropdown';
import * as i38 from 'primeng/components/paginator/paginator';
import * as i39 from 'primeng/components/inputtext/inputtext';
import * as i40 from 'primeng/components/datatable/datatable';
import * as i41 from 'primeng/components/multiselect/multiselect';
import * as i42 from 'primeng/components/togglebutton/togglebutton';
import * as i43 from '../../../app/shared/shared.module';
import * as i44 from '../../../app/users/user-list.component';
import * as i45 from '../../../app/users/user.component';
export const ProductModuleNgFactory:i0.NgModuleFactory<i1.ProductModule> = i0.ɵcmf(i1.ProductModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.BusyComponentNgFactory,i3.BusyBackdropComponentNgFactory,i4.ModalBackdropComponentNgFactory,
              i5.PopoverContainerComponentNgFactory,i6.TooltipContainerComponentNgFactory,
              i7.ToastContainerNgFactory,i8.UserListComponentNgFactory,i9.UserComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i10.FormBuilder,
          i10.FormBuilder,([] as any[])),i0.ɵmpd(4608,i10.ɵi,i10.ɵi,([] as any[])),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i11.NgLocalization,
              i11.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.Compiler,i12.createJitCompiler,
              ([] as any[])),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,
              i0.IterableDiffers,i0.ɵk,([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,
              i0.ɵl,([] as any[])),i0.ɵmpd(4608,i13.DomSanitizer,i13.ɵe,[i11.DOCUMENT]),
          i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i13.DomSanitizer]),i0.ɵmpd(4608,
              i13.HAMMER_GESTURE_CONFIG,i13.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,
              i13.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i13.ɵDomEventsPlugin(p0_0),new i13.ɵKeyEventsPlugin(p1_0),
                    new i13.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i11.DOCUMENT,i11.DOCUMENT,i11.DOCUMENT,i13.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i13.EventManager,i13.EventManager,[i13.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i13.ɵDomSharedStylesHost,i13.ɵDomSharedStylesHost,
              [i11.DOCUMENT]),i0.ɵmpd(4608,i13.ɵDomRendererFactory2,i13.ɵDomRendererFactory2,
              [i13.EventManager,i13.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i14.AnimationDriver,
              i15.ɵc,([] as any[])),i0.ɵmpd(5120,i14.ɵAnimationStyleNormalizer,i15.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i14.ɵAnimationEngine,i15.ɵb,[i14.AnimationDriver,
              i14.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i15.ɵe,
              [i13.ɵDomRendererFactory2,i14.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i13.ɵSharedStylesHost,(null as any),[i13.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i13.Meta,i13.Meta,
              [i11.DOCUMENT]),i0.ɵmpd(4608,i13.Title,i13.Title,[i11.DOCUMENT]),i0.ɵmpd(4608,
              i16.AnimationBuilder,i15.ɵBrowserAnimationBuilder,[i0.RendererFactory2,
                  i13.DOCUMENT]),i0.ɵmpd(5120,i17.BusyConfig,i18.BusyConfigFactory,
              ([] as any[])),i0.ɵmpd(4608,i19.BusyService,i19.BusyService,[[2,i17.BusyConfig]]),
          i0.ɵmpd(4608,i20.PositioningService,i20.PositioningService,([] as any[])),
          i0.ɵmpd(4608,i21.ComponentLoaderFactory,i21.ComponentLoaderFactory,[i0.ComponentFactoryResolver,
              i0.NgZone,i0.Injector,i20.PositioningService]),i0.ɵmpd(4608,i22.PopoverConfig,
              i22.PopoverConfig,([] as any[])),i0.ɵmpd(4608,i23.TooltipConfig,i23.TooltipConfig,
              ([] as any[])),i0.ɵmpd(4608,i24.ToastOptions,i25.CustomOption,([] as any[])),
          i0.ɵmpd(4608,i26.ToastsManager,i26.ToastsManager,[i0.ComponentFactoryResolver,
              i0.NgZone,i0.ApplicationRef,i24.ToastOptions]),i0.ɵmpd(4608,i27.ToastrService,
              i27.ToastrService,[i26.ToastsManager]),i0.ɵmpd(4608,i28.UserService,
              i28.UserService,[i29.Http]),i0.ɵmpd(4608,i30.UserDetailGuard,i30.UserDetailGuard,
              [i31.Router]),i0.ɵmpd(4608,i30.UserEditGuard,i30.UserEditGuard,([] as any[])),
          i0.ɵmpd(512,i10.ɵba,i10.ɵba,([] as any[])),i0.ɵmpd(512,i10.ReactiveFormsModule,
              i10.ReactiveFormsModule,([] as any[])),i0.ɵmpd(512,i11.CommonModule,
              i11.CommonModule,([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i13.ɵa,
              ([] as any[])),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any) => {
            return [i13.ɵc(p0_0,p0_1)];
          },[[2,i13.NgProbeToken],[2,i0.NgProbeToken]]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i13.BrowserModule,i13.BrowserModule,[[3,i13.BrowserModule]]),
          i0.ɵmpd(512,i15.BrowserAnimationsModule,i15.BrowserAnimationsModule,([] as any[])),
          i0.ɵmpd(512,i12.BusyModule,i12.BusyModule,([] as any[])),i0.ɵmpd(512,i32.ModalModule,
              i32.ModalModule,([] as any[])),i0.ɵmpd(512,i33.PopoverModule,i33.PopoverModule,
              ([] as any[])),i0.ɵmpd(512,i34.TooltipModule,i34.TooltipModule,([] as any[])),
          i0.ɵmpd(512,i35.ToastModule,i35.ToastModule,([] as any[])),i0.ɵmpd(512,i36.SharedModule,
              i36.SharedModule,([] as any[])),i0.ɵmpd(512,i37.DropdownModule,i37.DropdownModule,
              ([] as any[])),i0.ɵmpd(512,i10.FormsModule,i10.FormsModule,([] as any[])),
          i0.ɵmpd(512,i38.PaginatorModule,i38.PaginatorModule,([] as any[])),i0.ɵmpd(512,
              i39.InputTextModule,i39.InputTextModule,([] as any[])),i0.ɵmpd(512,i40.DataTableModule,
              i40.DataTableModule,([] as any[])),i0.ɵmpd(512,i41.MultiSelectModule,
              i41.MultiSelectModule,([] as any[])),i0.ɵmpd(512,i42.ToggleButtonModule,
              i42.ToggleButtonModule,([] as any[])),i0.ɵmpd(512,i43.SmSharedModule,
              i43.SmSharedModule,([] as any[])),i0.ɵmpd(512,i31.RouterModule,i31.RouterModule,
              [[2,i31.ɵa],[2,i31.Router]]),i0.ɵmpd(512,i1.ProductModule,i1.ProductModule,
              ([] as any[])),i0.ɵmpd(1024,i31.ROUTES,() => {
            return [[{path:'userlist',component:i44.UserListComponent},{path:'adduser',
                canDeactivate:[i30.UserEditGuard],canActivate:[i30.UserDetailGuard],
                component:i45.UserComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUHJvamVrdHkvU2VydmljZU1hcEFuZzQvU2VydmljZU1hcC9zcmMvU2VydmljZU1hcC93d3dyb290L2FwcC91c2Vycy91c2VyLW1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Qcm9qZWt0eS9TZXJ2aWNlTWFwQW5nNC9TZXJ2aWNlTWFwL3NyYy9TZXJ2aWNlTWFwL3d3d3Jvb3QvYXBwL3VzZXJzL3VzZXItbW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
